engines:
  eslint:
    enabled: true
    checks:
      no-var:
        enabled: false
      require-jsdoc:
        enabled: false
  rubocop:
    enabled: true
  scss-lint:
    enabled: true
  shellcheck:
    enabled: true
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
