ruby:
  enabled: true
  config_file: .rubocop.yml
haml:
  enabled: true
  config_file: .haml-lint.yml
eslint:
  enabled: true
  config_file: .eslintrc
sass-lint:
  enabled: true
  config_file: .sass-lint.yml
coffeescript:
  enabled: true
  config_file: coffeelint.json
