# This is a sample build configuration for Ruby.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ruby:2.2.3

pipelines:
  default:
    - step:
        script:
          - bundle install
          - gem install  --no-rdoc --no-ri 'brakeman' 'bundler-audit'
          - cp config/secrets.codeship.yml config/secrets.yml
          - RAILS_ENV=test bundle exec rake db:schema:load
          - echo "require 'digest/sha1'" > config/initializers/access.rb
          - echo "NZSL_ADMIN_ACCESS = { 'text' => Digest::SHA1.hexdigest('test') }" >> config/initializers/access.rb
          - bundle-audit check --update
          - bundle exec rubocop
          - brakeman --run-all-checks --exit-on-warn .
          - RAILS_ENV=test bundle exec rspec spec
