---
# Skylight can take configuration from environment variables. We do that whenever possible because it allows us to:
#
# 1. Change settings at runtime.
# 2. Have different settings in different environments.
#
# For example, authentication comes from the `SKYLIGHT_AUTHENTICATION` environment
# variable. The authentication token should **never** be added to this file.
# For details, see
# https://www.skylight.io/support/advanced-setup#setting-authentication-tokens
#
# The authentication token for the application.
# authentication: SEE COMMENT ABOVE
